---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true

- name: Persist iptables
  ansible.builtin.command: netfilter-persistent save
  changed_when: true
  become: true
