---
- name: Restart monitoring stack
  ansible.builtin.command:
    cmd: docker compose up -d --force-recreate
    chdir: "{{ monitoring_dir }}"
  changed_when: true
  become: true

- name: Persist iptables
  ansible.builtin.command: netfilter-persistent save
  changed_when: true
  become: true
